### KELOMPOK 10 :
1. MUHAMMAD ADE SULISTIANSYAH - 103102400045
2. IZAM ROSIAWAN - 103102400049
3. NOVENA AURELIA LUISMA - 103102400050
4. FEYSHA KAMILA PRACILYA - 103102400054

### Mengenali Karakteristik Data

Saat saya pertama kali melihat sebuah array, saya harus tahu dimensinya. Dimensi atau shape adalah jumlah baris dan kolom yang menyusun array saya. Misalnya, array dua dimensi 4x5 memiliki 4 baris dan 5 kolom. Untuk memeriksa ini, saya cukup menggunakan atribut pada objek array saya. Ukuran atau size adalah total jumlah elemen di dalam array, yang bisa didapatkan dari atribut.

In [1]:
import numpy as np

# Membuat array 2x3
data_matrix = np.array([[10, 20, 30], [40, 50, 60]])

# Memeriksa karakteristik data
print("Bentuk (Shape) array:", data_matrix.shape)
print("Ukuran (Size) array:", data_matrix.size)
print("Tipe data (Dtype) array:", data_matrix.dtype)

Bentuk (Shape) array: (2, 3)
Ukuran (Size) array: 6
Tipe data (Dtype) array: int64


### Tipe Data




NumPy mendukung berbagai tipe data numerik yang efisien untuk komputasi ilmiah. Tipe data ini termasuk integer (int), unsigned integer (uint) untuk nilai non-negatif, float untuk bilangan desimal, complex untuk bilangan kompleks, dan bool untuk nilai logis. Anda bisa secara eksplisit menentukan tipe data saat membuat array dengan argumen dtype

In [2]:
# Membuat array dengan tipe data float eksplisit
data_float = np.array([1, 2, 3], dtype=np.float64)
print("Array float:", data_float)
print("Tipe data float:", data_float.dtype)

# Membuat array dengan tipe data integer eksplisit
data_int = np.array([1.5, 2.8, 3.1], dtype=np.int64)
print("Array integer dari float (terpotong):", data_int)
print("Tipe data integer:", data_int.dtype)

Array float: [1. 2. 3.]
Tipe data float: float64
Array integer dari float (terpotong): [1 2 3]
Tipe data integer: int64


### Membuat Array Dengan Berbagai Teknik

NumPy menyediakan berbagai fungsi untuk membuat array dengan cepat, yang sangat berguna dalam analisis data.

* Dari List Python: Metode paling sederhana. Anda bisa membuat array satu dimensi dari list biasa, atau array multidimensi dari list bersarang (list di dalam list).

* Array dengan Nilai Khusus:

  * np.zeros((3, 3)) membuat matriks 3x3 yang semua elemennya nol.

  * np.ones((2, 4)) membuat matriks 2x4 yang semua elemennya satu.

  * np.full((3, 2), 7) membuat matriks 3x2 yang semua elemennya bernilai 7.

* Array dengan Urutan Angka:

  * np.arange(0, 10, 2) membuat array mulai dari 0 hingga kurang dari 10 dengan langkah 2.

  * np.linspace(0, 1, 5) membuat array dengan 5 elemen yang terdistribusi merata antara 0 dan 1.

* Array dengan Nilai Acak:

  * np.random.rand(2, 2) membuat array acak dengan distribusi seragam.

  * np.random.randn(3, 3) membuat array acak dengan distribusi normal standar.

In [3]:
# Contoh membuat array dengan berbagai teknik
print("Array nol:\n", np.zeros((2, 2)))
print("\nArray berurutan:\n", np.arange(0, 5))
print("\nArray acak normal:\n", np.random.randn(2, 2))

Array nol:
 [[0. 0.]
 [0. 0.]]

Array berurutan:
 [0 1 2 3 4]

Array acak normal:
 [[0.0088917  0.26891899]
 [0.23005806 0.71639042]]


### Membuat Matriks

Matriks adalah array dua dimensi. NumPy memiliki beberapa fungsi khusus untuk membuat matriks dengan struktur tertentu yang sering muncul dalam aljabar linear.

* Matriks Identitas (np.identity): Matriks ini memiliki nilai 1 di diagonal utamanya dan 0 di tempat lain. Berguna dalam banyak operasi matriks.

* Matriks Diagonal (np.diag): Membuat matriks dengan elemen yang diberikan hanya pada diagonal utama.

In [4]:
# Contoh membuat matriks
print("Matriks Identitas 4x4:\n", np.identity(4))
print("\nMatriks Diagonal dari [10, 20, 30]:\n", np.diag([10, 20, 30]))

Matriks Identitas 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matriks Diagonal dari [10, 20, 30]:
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


### MENGIMPLEMENTASIKAN OPERASI LOGIKA MATEMATIKA MENGGUNAKAN BOOLEAN

In [ ]:
A = (2 > 1)   # True, karena 2 memang lebih besar dari 1
B = (5 < 3)   # False, karena 5 tidak lebih kecil dari 3

print("A =", A)
print("B =", B)
print("A AND B =", A and B)     # AND: True kalau A dan B sama-sama True
print("A OR B  =", A or B)      # OR: True kalau salah satu True
print("NOT A   =", not A)       # NOT: membalik nilai A
print("A -> B  =", (not A) or B) # Implikasi: salah hanya kalau A True dan B False
print("A ↔ B   =", A == B)      # Ekuivalen: True kalau A dan B sama

A = True
B = False
A AND B = False
A OR B  = True
NOT A   = False
A -> B  = False
A ↔ B   = False


Penjelasan:
Mengimplementasikan operasi logika matematika menggunakan boolean artinya kita menerapkan aturan logika (benar–salah) ke dalam program komputer. Dalam matematika, sebuah pernyataan bisa bernilai benar atau salah. Misalnya: “2 lebih besar dari 1” adalah benar, sedangkan “5 lebih kecil dari 3” adalah salah. Pernyataan ini disebut boolean di pemrograman (True untuk benar, False untuk salah). Dengan boolean, kita bisa melakukan operasi logika seperti:
	•	AND (dan): hasilnya benar kalau dua-duanya benar.
	•	OR (atau): hasilnya benar kalau salah satu benar.
	•	NOT (tidak): membalik nilai, yang benar jadi salah, yang salah jadi benar.
	•	Implikasi: “jika A maka B”, salah hanya jika A benar tapi B salah.
	•	Ekuivalen: benar kalau A dan B sama nilainya.